### ISSUE TITLE
ファイルパス文字

### ISSUE THREAD

**Issue by nobsun** [haskell-jp/recipe-collection#11]
ファイルパスとかファイル名に非ASCII文字とか空白とかあるのは、
コードのパッケージ化のときにディレクトリ構成のマッピングに余分に情報が必要になるのと、
非日本語のOSをつかっているユーザにはちょっと辛いかも。。。

**Comment by kayhide** [comment]
ファイル名の日本語、やっぱり気になりますよね。
まず日本語のメリットとしては、

- ファイルリストがそのまま目次になる
- つまり目次とファイルのマッピングメンテが不要になる

というものがあります。
ファイルシステムの問題ももちろん考えたのですが、

- 日本コミュニティであること
  - -> 非日本語 OS ユーザーをそこまで重視するか？
- github のブラウザテキストから編集できる
  - -> 仮にファイルシステムが非対応でも逃げ道がある

の事情を踏まえて、日本語でもよいかな、と判断しました。

パッケージについても、あくまでもこの企画の目的は、

- 有用なコンテンツを必要としているユーザーに届けること

であり、

- パッケージにすること自体

は、それより重要度は低いと考えています。

ユーザビリティやメンテナビリティを損なわずにパッケージ化できるなら、それは賛成です。
ですが、パッケージ化するために使いにくくなる、メンテコストがあがる、というのであれば一歩立ち止まって考えたいところです。

パッケージ化自体がコンテンツとして有用である、という考えもあるかと思いますが、さすがにそこまでやるのはこのレシピの範囲を越えているのではないか、と判断しています。

**Comment by nobsun** [comment]
> 日本コミュニティであること
> -> 非日本語 OS ユーザーをそこまで重視するか？

私は日本語対応OSを使っていますが、コマンドラインで操作することが多いので、
git clone して ls とやったとたん、うへぇー、と思ってしまいました。

> github のブラウザテキストから編集できる
> -> 仮にファイルシステムが非対応でも逃げ道がある

手なれたエディタで編集したいので、ブラウザから編集できてもあまりうれしくないかも。
とはいえ、単に、私個人の好みにすぎないかもしれませんね。

パッケージ化については、レシピ集を参考にしながらも、独立したものとしてもようさそうですし、
特にどうしてもという拘泥はありません。

**Comment by kayhide** [comment]
> 私は日本語対応OSを使っていますが、コマンドラインで操作することが多いので、
git clone して ls とやったとたん、うへぇー、と思ってしまいました。

いや、同感です。
正直いうと僕も日本語ファイル名は、うへぇー、です。
コマンドラインで補完きかないし。

> 手なれたエディタで編集したいので、ブラウザから編集できてもあまりうれしくないかも。

それもその通りだと思います。

ここで重視したのは、10 人の凄腕よりも 1 万人の普通の人が動いた方が仕事が進む、という視点です。
それなら、1 万人の普通の人にとってどういうやり方がいいかな、と考えた結果がいまの方針に反映されています。

**Comment by hiratara** [comment]
ディレクトリ名はASCIIにして、 https://github.com/haskell-jp/recipe-collection/blob/master/README.md を目次にしてここから日本語でリンクを貼るのはいかがでしょうか。

> 有用なコンテンツを必要としているユーザーに届けること

が一番重要なのは間違いありませんが、markdownが日本語であり、きちんとした目次があってクリックによって遷移できるのであれば、問題は解決できていると言えるかと思います。

> ファイルリストがそのまま目次になる
> つまり目次とファイルのマッピングメンテが不要になる

これは解決できませんが、何らかの方法で自動化すれば済む話ですし、それほど重要ではないと思いました。

それよりも、例えば #10 を TravisCI などでCIを回そうとしたときなど、なんらかの自動化を行う場合にファイルシステムが障壁で余計な手間がかかるほうが、メンテナンスコストが高くなるように思えます。

**Comment by YoshikuniJujo** [comment]
僕もはじめは「うへぇー」でした。
ただ、漢字直接入力を使っているので、補完の問題が、ある程度すくなくなる点と、
英語力のとぼしい僕としては、ファイル名を考える手間がなくなることから、
この問題に対しては中立か、やや、日本語ファイル名推しよりの立場です。

**Comment by kayhide** [comment]
この問題は GitHub でホスティングする、という視点が絡んでます。
#12

**Comment by kayhide** [comment]
当面 GitHub でホスティングするという方針でいきますので、ファイルパスは日本語まじりとさせてください。
ホスティングを移動する際にはまた別途検討しましょう。

日本語パスで具体的な問題が起こった場合は個別にイシューをあげてくださいませ。
