### ISSUE TITLE
コンテンツのホスティング方法

### ISSUE THREAD

**Issue by arowM** [haskell-jp/recipe-collection#12]
おそらく、今のレポジトリの構成だと、github上にそのままマークダウンをおいてホスティングする想定だと思います。

もしこれを静的ファイルに変換して`haskell.jp`ドメイン下で公開したら、アクセスを稼ぐのにとても有力なコンテンツになり、`haskell.jp`全体のドメインパワーも高まって、SEO的にとても素敵なことになると思います。

**Comment by kayhide** [comment]
> おそらく、今のレポジトリの構成だと、github上にそのままマークダウンをおいてホスティングする想定だと思います。

そうした方がユーザーにとってもメンテナーにとってもメリットが大きいのではないかな―、と思っています。
まだ流動的ですが。

> もしこれを静的ファイルに変換してhaskell.jpドメイン下で公開したら、アクセスを稼ぐのにとても有力なコンテンツになり、haskell.jp全体のドメインパワーも高まって、SEO的にとても素敵なことになると思います。

確かに haskell.jp の SEO 視点ではそうですね。

一方で github 上でホスティングしていれば、 github.com という超強力なドメインパワーを間借りすることができます。
このドメインパワーで github 上のコンテンツでアクセスを集めて、そこから適宜 haskell.jp にアクセスを流す、というやり方も有効だと思います。

これなら、仮に haskell.jp のドメインが何らかの事情で吹っ飛んでしまっても、github.com が吹っ飛ばない限りアクセスは確保できます。

**Comment by kakkun61** [comment]
コンテンツは GitHub で管理しつつ、変換かまして haskell.jp にデプロイがいいのではないかと思います。

今の GitHub での Markdown だと、レシピをざざっと読み漁るのがしにくいと思っています。Markdown のページとディレクトリーのページを行ったり来たりしないといけないので。ですが、管理という点では項目ごとにページが分かれているのはいいことだと思っています。

haskell.jp ドメインに置いた方がいいかというより、GitHub での Markdown が読み物として読みやすいかという視点ですね。

**Comment by kayhide** [comment]
@kakkun61 
整形してデプロイした方が読み物として読みやすくなるのはそのとおりだと思います。
GitHub でホスティングすると、確かにその点は損なわれるでしょうね。

一方、GitHub でホスティングしていると、その在り方自体がすでに読者へのメッセージになります。
つまり「このコンテンツは作るのもオープンである」というメッセージです。
このメッセージを受け取って、イシューを作ってくれたりプルリクしてくれたりするユーザーがでてくることを期待しています。

世の中にこれだけ OSS が力を持っているのですから、ドキュメントもその方法論で発展させられるのではないでしょうか。

**Comment by arowM** [comment]
@kayhide 
もし、github上でホストしたいという結果が先にあっての理由付けであれば、別にgithub上でホストしてもhaskell.jp上にホストしてもどちらでも個人的にはまったく問題ないので、あくまで参考の意見ですが、

> 一方、GitHub でホスティングしていると、その在り方自体がすでに読者へのメッセージになります。
> つまり「このコンテンツは作るのもオープンである」というメッセージです。
> このメッセージを受け取って、イシューを作ってくれたりプルリクしてくれたりするユーザーがでてくることを期待しています。

これについてはgithubでソースコードを管理していて、誰でもプルリクやイシュー歓迎状態であれば別にあえてgithub上だけで公開しなくても問題ないのかなと思います。
実際、多くのオープンソースライブラリのドキュメントがgithub pagesなどで別ドメイン上にホスティングされ、「プルリクはgithubでよろしくね〜」というスタンスでやっているので。

ただ、冒頭でも言及したとおり、github上でそのまま公開することが最初から決定事項になっているのであれば、
別にそれが適切かどうかなんて細かいことを気にして何もはじまらないより、さっさと始めた方がいいと僕は思うので、github上のみでのホスティングでも特に問題ないです！

**Comment by kayhide** [comment]
@arowM 
了解です！

**Comment by kakkun61** [comment]
> 別にそれが適切かどうかなんて細かいことを気にして何もはじまらないより、さっさと始めた方がいいと僕は思うので、github上のみでのホスティングでも特に問題ないです！

自分も同意見ですー

**Comment by kayhide** [comment]
@arowM @kakkun61 
> github上でホストしたいという結果が先にあっての理由付けであれば

推察のとおり、これが先にあっての理由付けです。
github 上でホスティングしようと考えていますので、よろしくお願いします。

**Comment by arowM** [comment]
そしたら、逆引き辞典の旗振り役をしてくださっている @kayhide さんのご決断にしたがって、
github上でホスティングするということで、こちらのissueはクローズします！

**Comment by YoshikuniJujo** [comment]
コンテンツを充実させることと並行して、さまざまなファイル形式での提供を、すこしずつ用意していけばいいかと思います。HTMLでの提供、1ファイルのHTMLでの提供、PDFでの提供などなど。ただ、最新版であり、主になるものはgithub上での閲覧とするのが良いかと。それぞれの形式への変換をコマンド一発でできるような仕組みを、コンテンツが、充実してきたころに作ると良いかと思います。
