### ISSUE TITLE
純粋な関数を返り値とともに示す場合の書式

### ISSUE THREAD

**Issue by kayhide** [haskell-jp/recipe-collection#13]
#### 案1 たたき台

```haskell
replicate 3 "hoge"
-- ["hoge","hoge","hoge"]
```

##### pros

- コピペがラク
- 表記が簡潔

##### cons

- このままではコンパイルできない
- 初学者には、どう使えばよいかわからず混乱しかねない
- 手近な書籍でこの書式を採用しているものが見当たらない

#### 案2 定義つき

```haskell
hoge3 :: [String]
hoge3 = replicate 3 "hoge"
-- ["hoge","hoge","hoge"]
```

##### pros

- コンパイルできる
- 型も併記できる

##### cons

- この方法で返り値をコメント書きしている書籍は見当たらない

#### :star: 案3 REPL （採用）

```haskell
Prelude> replicate 3 "hoge"
["hoge","hoge","hoge"]
```

##### pros

- 実行方法が明確
- REPL の見た目がそのままで書き手がコピペしやすい

##### cons

- 初学者が REPL 触るだけで終わってしまう懸念がある
- do 記法を使うと複数行になって扱いづらい

#### 案4 doctest

```haskell
-- >>> replicate 3 "hoge"
-- ["hoge","hoge","hoge"]
replicate :: Int -> a -> [a]
```

##### pros

- doctest にかけられる

##### cons

- doctest の説明が必要だろう

#### 案5 main

```haskell
main = do
  let hoge3 = replicate 3 "hoge"
  print hoge3 -- ["hoge","hoge","hoge"]
```

##### pros

- 実行方法が明確
- ユーザの利用シーンに最も近いはず

##### cons

- ボイラーテンプレートとして `main = do` とインデントが入る

-----

「すごいHaskellたのしく学ぼう！」「プログラミングHaskell」「関数プログラミング実践入門」「Haskellによる関数プログラミングの思考法」では、案2と案3の組み合わせで書かれている。

REPL のプロンプトは `ghci>`、`>`、`Prelude>` と、バリエーションがいろいろ。

「Haskell Programming from first principles」では一部 doctest を使っている。

**Comment by nobsun** [comment]
有効な .ghci ファイルに :def source readFile と書いておくと、
ghciのセッションから ghci スクリプトファイルを :source foo.ghci のように呼べるので、

案1 たたき台 でもコピペでいけます。

https://github.com/haskell-jp/recipe-collection/blob/master/%E6%97%A5%E4%BB%98%E3%81%A8%E6%99%82%E5%88%BB/%E4%BB%8A%E6%97%A5%E3%81%AE%E6%97%A5%E4%BB%98%E3%82%92ISO8601%E5%BD%A2%E5%BC%8F%E3%81%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.md#今日の日付をiso8601形式で表示する

**Comment by hiratara** [comment]
案5を書きました。

> 案1 たたき台 でもコピペでいけます。

じっくり頭から読んでコード片を動かしていくコンテンツであれば、コピペで動かすための手法を考えてそれを読者に覚えてもらうというのは有効かと思います。

しかしこのコンテンツは、今まさにHaskellのプログラムを書いていて課題を抱えてる読者が、このページを見てどれだけ短時間で問題解決ができるかが重要であるという認識です。ですので、単にコピペで実行できるというだけではなく、読者の手元の書いている途中のコードにコピペできる（特に `x <- mx` と `let x = y` の区別もおぼろげなレベルな読者でも、どこにどういう風にコピペすればいいか把握して、手元のコードに組み込んで実行できる)ことが重要だと思いました。

**Comment by nobsun** [comment]
> 今まさにHaskellのプログラムを書いていて課題を抱えてる読者が、このページを見てどれだけ短時間で問題解決ができるかが重要であるという認識です。

なるほど了解です。問題解決のためのレシピ集であってプログラミングチュートリアルではない。

**Comment by YoshikuniJujo** [comment]
僕としては、レシピを読んだ読者が、もっとも試しやすいのがREPLなので、REPL推しです。
ただ、この意見は、実際の開発でもREPLを多用しているという、僕自身の開発手法によるバイアスがかかっていますが。

**Comment by YoshikuniJujo** [comment]
REPLをあまり使わない開発スタイルを想定すると案5がいいのかもしれません。ただ、実用的ではあるけれど、あまり美しくないのが...

**Comment by nobsun** [comment]
利用例を追加した記事に修正してみました。

https://github.com/haskell-jp/recipe-collection/blob/master/%E6%97%A5%E4%BB%98%E3%81%A8%E6%99%82%E5%88%BB/%E4%BB%8A%E6%97%A5%E3%81%AE%E6%97%A5%E4%BB%98%E3%82%92ISO8601%E5%BD%A2%E5%BC%8F%E3%81%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.md#%E4%BB%8A%E6%97%A5%E3%81%AE%E6%97%A5%E4%BB%98%E3%82%92iso8601%E5%BD%A2%E5%BC%8F%E3%81%A7%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B

**Comment by hiratara** [comment]
> 「すごいHaskellたのしく学ぼう！」「プログラミングHaskell」「関数プログラミング実践入門」「Haskellによる関数プログラミングの思考法」では、案2と案3の組み合わせで書かれている。

世に出回っている書籍を見ると、これが現実解かもしれませんね。REPLを使うことは前提に、長いコードは案2の書式を使ってコード片を書いた上で、REPL上で評価して結果を見せる、と。

@YoshikuniJujo さんのおっしゃる通り確かに開発中でもREPLは使うので、そういう意味では↑に書いた書式でも案5のPROSに書いた「> ユーザの利用シーンに最も近い」が当てはまる気がしました。

なお、このissueは

> 純粋な関数を返り値とともに示す場合の書式

なので、 `IO` が絡むレシピはこのissueで決める方針とは別で、案5の `main` と `print` を使ってsnippetを作るのが一番読者にとってとっつきやすいかなと思います。

**Comment by kayhide** [comment]
ここまでの議論を踏まえると、純粋な関数を返り値とともに示す場合は

案3 REPL

がよさそうですね。

**Comment by hiratara** [comment]
純粋ではあるものの、複数行にまたがるようなサンプルは案2の記法でしょうか？

案3のREPLにこだわるのでしたら `:{` を使うことになってきますが、どうでしょう。

**Comment by nobsun** [comment]
関数適用の値の表示を含めIOアクションの結果の表示と、定義は分けて示すべきと個人的にはおもいます。

定義は foo.hs ファイルに書いて、REPLにロードする。
式評価の表示やIOアクションの結果表示は foo.ghci ファイルに書いて、REPLコマンドとして実行する。

で行けるように分けると良いような気がします。

**Comment by hiratara** [comment]
> 式評価の表示やIOアクションの結果表示は foo.ghci ファイルに書いて、REPLコマンドとして実行する。

こちらは .ghci ファイルを用意しなくても案3のような記法で十分かと思ったのですが、 foo.ghci を作った方がいい理由が何かある感じです？

**Comment by nobsun** [comment]
foo.ghciというファイルを作るかどうかは、それぞれでいいと思いますが、
分離できるということは、重要だと思います。
コードブロックの部分をまともに保守しようとすると、動作確認をするときに、
部分的に有効は表現部分を選択抽出して動作させてみなければならないのと、
そのまんま、貼り付けるだけでよいのとではずいぶん違うので。。。

**Comment by kayhide** [comment]
@hiratara 
> 純粋ではあるものの、複数行にまたがるようなサンプル

ですが、具体的にどのようなものを考えているか、例を出していただけますでしょうか？

**Comment by hiratara** [comment]
例えばですが、こういうのです。
https://gist.github.com/moznion/3198484

この例はガード使ってるからというのもありますけど、 `IO` に限らず処理が複雑で一行に書ききれなくなると自然と複数行になりますよね？ `where` 句で定義したり `let` ～ `in` 式使ってバラしたり。

もしくは中身あまり読んでませんけど、 `IO` 以外のモナドで `do` 記法を使うと複数行になりますよね。
https://gist.github.com/dmatveev/5993223

ということで、案2のような、別の `*.hs` ファイルに書けるような記法を使う必要が出てくることもあるのではないかと思いました。

**Comment by kayhide** [comment]
なるほど。
例示ありがとうございます。

> 例えばですが、こういうのです。
> https://gist.github.com/moznion/3198484

こちらは「定義」の方ですね。
このイシューでは「評価」（関数に引数を適用して返り値をだす）の方を扱っていますので、「定義」の書き方については分けて考えましょう。

> もしくは中身あまり読んでませんけど、 IO 以外のモナドで do 記法を使うと複数行になりますよね。
https://gist.github.com/dmatveev/5993223

これは確かにそうですね。
do 記法で書いた純粋な関数を評価して返り値を表示する、となると複数行になりそうです。

**Comment by hiratara** [comment]
> このイシューでは「評価」（関数に引数を適用して返り値だす）の方を扱っています

おお、そうでしたか。となると、私はまったくissueで議論すべき内容を理解できていませんでした、すみません。

関数呼び出しだけであればよほど鬼のように引数が長くなければ1行に収まるかと思います。

ちなみに、「定義」の記法についてもまた別のissueが起票されるのでしょうか？

**Comment by kayhide** [comment]
いえいえ、イシューの説明もやや不十分だったかもしれません。
こちらこそ、すみません。

> 関数呼び出しだけであればよほど鬼のように引数が長くなければ1行に収まるかと思います。

そうですよね。
例としてそういうものがでてくるのかな、と思ってしまっていました。

> ちなみに、「定義」の記法についてもまた別のissueが起票されるのでしょうか？

定義については、いまのところ方針が分かれそうな気配がないので様子見中です。

**Comment by kayhide** [comment]
では、この件は案3 の REPL でいくことにしましょう。

**Comment by kayhide** [comment]
方針が定まったのでクローズします。
