### ISSUE TITLE
IOが絡む場合のサンプルコードの方針

### ISSUE THREAD

**Issue by kayhide** [haskell-jp/recipe-collection#14]
#### 案1 main関数を書く

```haskell
main = do
  ct <- getCurrentTime
  print ct -- > 017-04-06 09:50:31.150551 UTC
```

##### pros

- スタンドアロン（それだけで実行可能）なコードになる
- 「これは単なる評価ではなく、なんらかの入出力がからんできますよ」というところが、感覚的によくわかる

#### 案2 必要な部分だけ書く

```haskell
ct <- getCurrentTime
print ct -- > 017-04-06 09:50:31.150551 UTC
```

##### pros

- 簡潔である

#### 案3 REPL形式

```haskell
> ct <- getCurrentTime
> ct
2017-04-06 09:50:31.150551 UTC
```

##### pros

- REPLで実行できることが伝わりやすい

##### cons

- 返り値と出力の区別がつかない

**Comment by kayhide** [comment]
#13 から派生。

いまのところあまり話題になっていませんが、議論の場としてイシューにしました。
議論が進むに従ってトップのコメントを編集していきます。

**Comment by YoshikuniJujo** [comment]
「案1 main関数を書く」に1票。
レシピは簡単に試せるのが一番かと。

**Comment by nobsun** [comment]
main 関数を書かなくても試せますよね。
もちろんスタンドアロンのコマンドを作るのが主体のレシピならmainを書くべきでしょうけど、
単なる部品ならたとえば、

ct <- getCurrentTime
print ct  -- > 2017-04-06 09:50:31.150551 UTC

で十分だ（個人的にはそうしたほうがよい）と思います。

**Comment by hiratara** [comment]
`main` や `do` を略すと初学者にとっては書かれてるコード片の使い方が自明ではないと考えています。 `main` と `do` を書くだけで初学者にも優しくなるなら、そのほうがいいのではないかと。

個人的には https://lotz84.github.io/haskellbyexample/ が理想的な形だと思ってました。（あれ、じゃあ初めからこれを日本語に訳せばいいんじゃ（笑））

**Comment by nobsun** [comment]
> main や do を略すと初学者にとっては書かれてるコード片の使い方が自明ではないと考えています。
> main と do を書くだけで初学者にも優しくなるなら、そのほうがいいのではないかと

はい、同意です。ただ、 main と do を書いても自明にはならない気がします。
（これは私が、imperative な スタイルが苦手だからですが。。。）

> あれ、じゃあ初めからこれを日本語に訳せばいいんじゃ（笑）

ですね。^^/

**Comment by kayhide** [comment]
初学者をどこまで考慮するか、ですね。
現在並行して入門コンテンツを作成中ですが、そちらにある程度は委ねられると考えています。

それを踏まえて、

- main 関数が何なのか
- REPL とは何なのか

は、少なくとも知っている、という前提で読者を想定してもよいかと思います。

レシピ集は教科書ではなく、むしろ辞書や参考書の類といえるかもしれないですね。

**Comment by lotz84** [comment]
[Haskell by Example](https://lotz84.github.io/haskellbyexample/)は [Go by Example](https://gobyexample.com/) をHaskellで書いてみた、がコンセプトなのでどこまで輸入できるかはわかりませんが使えるところがあれば勝手に使っていただいて大丈夫です(^^)

説明の流れで main 関数を組み立てたいときもあれば、REPLで簡単に実行した結果を載せたいときもあると思うのでどちらだけに統一する必要はないのかなと思っています。
ただREPLかそうでないかの区別はついたほうがいいと思うので、REPLの場合であれば

```haskell
> purStrLn "Hello"
"Hello"
```

のようにコードの先頭に `> ` をつけて書くほうがわかりやすいかと思います。

**Comment by hiratara** [comment]
REPLの話も出たので、一応案3を追記しておきました。

**Comment by YoshikuniJujo** [comment]
僕のなかでは、案1か案3のどちらかかな、と考えています。「試しやすい」というところが、ポイントかと。それと、案1を案3より推す理由のひとつとして、IOのからむ関数について、「これは単なる評価ではなく、なんらかの入出力がからんできますよ」というところが、感覚的によくわかるということがあります。IOのからむレシピと、純粋なレシピとを、視覚的に区別できるところがクールな気がします。

**Comment by kayhide** [comment]
@hiratara 

> REPLの話も出たので、一応案3を追記しておきました。

ありがとうございます。

```haskell
> ct <- getCurrentTime
> print ct
2017-04-06 09:50:31.150551 UTC
```

この例ですが、`ct` や `print` の意義がちょっとわかりません。

書くなら、

```haskell
> getCurrentTime
2017-04-06 09:50:31.150551 UTC
```

になるかと思います。
`ct` をあとで使いたいというモチベーションであれば、

```haskell
> ct <- getCurrentTime
> ct
2017-04-06 09:50:31.150551 UTC
```

でしょうか。

**Comment by YoshikuniJujo** [comment]
それと、IOが本質的でない場合にはREPLで書くほうがいいかな、と考えます。
例としては、さきほど僕が書いた「2つの日時の差を...」 #9 などは、
計算例を挙げるために、サンプルの日時の入手にgetCurrentTimeを使っていますが、
diffUTCTimeのほうは純粋なので、REPLを使用してみました。

**Comment by kayhide** [comment]
REPL で IO を使う場合、表示されたものが、

- 返り値なのか
- 出力なのか

がわからない、という紛らわしさはありますね。

```haskell
> show "Hello"
"\"Hello\""
```

は返り値ですが、

```haskell
> putStrLn "Hello"
Hello
```

は出力です。

**Comment by YoshikuniJujo** [comment]
そうですね。なので僕としては、REPLでIOを使うのは、上記で挙げた「2つの日時の...」の例のように、説明のための補助として、使うときにとどめておいたほうが、初心者の混乱をふせげるのではないかと考えています。

**Comment by nobsun** [comment]
REPLの使い方をレシピ番号０として掲載するというのはどうでしょう。

**Comment by hiratara** [comment]
> この例ですが、ct や print の意義がちょっとわかりません。

こちらは案1と案2をコピペしただけなので意味は無いです。重要なのは `> ` のプロンプトを書くことと、結果行にはプロンプトも何も書かないことです。つまり、REPLでユーザが見るのと同じ記法であること、だけが要点でした。

**Comment by hiratara** [comment]
> REPLでIOを使うのは ... 説明のための補助として、使うときにとどめて

私もREPLの懸念点とその解決法(引用した部分)について、まったく同じように考えておりました。

> REPLの使い方をレシピ番号０として掲載するというのはどうでしょう。

レシピ0番(?)としてREPLの解説を用意することには賛成です。

ただ、このコンテンツは基本的にGoogle検索で特定のレシピへ飛んできて、読み終わったら即離脱する性質のものであると思うので、レシピ0番を読者がすでに読んでることを期待すべきではないかと思います。レシピ0番へのリンクを張った上でその内容を使う、程度だったらありかともいます。

**Comment by nobsun** [comment]
レシピのコードブロックを使って示してあるといいことに３種類あるようにおもいます。
それぞれ、定義、評価例、コピペ用コードであることを明示するというのはどうでしょう。

1. 定義（既存のAPIの使用レシピの場合は型シグネチャ）
```
getCurrentTime :: IO UTCTime
```
2. 評価あるいは実行例
```
ghci> getCurrentTime
2017-04-06 09:50:31.150551 UTC
```
3. コピペ利用するためのコード片
```
ct <- getCurrentTime
putStrLn (show ct)
```

**Comment by hiratara** [comment]
> 3. コピペ利用するためのコード片

私はやはりこれには反対の立場でして、「この記法ではトップレベルに書くべきなのか `do` ブロック内に書くべきなのか、その他の場所に書くべきなのかが自明にわからない」というのが私の考え方です。Template Haskellなどが出てくると、余計書ける場所を把握するのが難しくなります。

なので、逆に言えば、「以下のコード片は `IO` モナドの `do` ブロック内に書いて下さい」と常に補足するのであれば異論はありません。

案1は `*.hs` ファイルのトップレベルに書く、案3はREPL内で書く、という意味ではっきりしているのが利点と考えています。

**Comment by YoshikuniJujo** [comment]
僕の実体験としても、「コード片」の使いかたがわからず、発狂しそうになることがあるので、スタンドアロンで、「動くコード」を載せてあげるのが親切なのでは、とは思います。

**Comment by nobsun** [comment]
ああそうですね。IOの場合は、3.はmainの定義全体を書くほうがいいですねぇ。

**Comment by nobsun** [comment]
3. コピペしやすい利用例コード
```
main = do
  ct <- getCurrentTime
  putStrLn (show ct)
```

**Comment by nobsun** [comment]
私としては、どれかではなくて３種類とも揃っていて欲しいですねぇ。

**Comment by kayhide** [comment]
> こちらは案1と案2をコピペしただけなので意味は無いです。重要なのは > のプロンプトを書くことと、結果行にはプロンプトも何も書かないことです。

了解です。
ではその趣旨を反映して重要な点が明確になるように修正しておきました。

**Comment by kayhide** [comment]
> REPLの使い方をレシピ番号０として掲載するというのはどうでしょう。

これはレシピ集全体に関わることなので、トップの README に書くのがよいかな。
長くなるようなら、別に分けましょう。

**Comment by YoshikuniJujo** [comment]
案3の例に'ct <- 'がぬけていたので追加しておきました。

**Comment by hiratara** [comment]
> 私としては、どれかではなくて３種類とも揃っていて欲しいですねぇ。

3が「3. コピペしやすい利用例コード」という話であれば、 @nobsun さんの挙げられている3パターン全て異論ありません。わかりやすく整理されていて良いと思います 😀 

> 1. 定義（既存のAPIの使用レシピの場合は型シグネチャ）
> 2. 評価あるいは実行例
> 3. コピペしやすい利用例コード

**Comment by kayhide** [comment]
話を戻しまして、表題の「IOが絡む場合のサンプルコードの方針」としては

- 基本的に案1 main を書く
- 適宜、案3 REPL も使うが、その場合は出力と返り値が区別できない点に留意する

が落とし所でしょうかね。

**Comment by kayhide** [comment]
議論が落ち着いたようなのでクローズします。
wiki に反映しておきました。
https://github.com/haskell-jp/recipe-collection/wiki/%E5%88%9D%E6%9C%9F%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E4%BD%9C%E6%88%90%E3%81%AE%E3%81%8A%E6%89%8B%E4%BC%9D%E3%81%84%E6%96%B9%E6%B3%95#io%E3%81%8C%E9%96%A2%E4%BF%82%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88
